name: Build

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-tags: 'true'
        fetch-depth: 0

    - name: 3rd party check
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $CACHE_KEY=git ls-files -s wic_heic\3rdparty | git hash-object --stdin
        echo "Cache key: $CACHE_KEY"
        echo "CACHE_KEY=$CACHE_KEY" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Cache 3rd party build
      id: cache-ext
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-3rdparty-${{ env.CACHE_KEY }}
        path: |
          .\wic_heic\3rdparty\_out
          .\wic_heic\3rdparty\_tmp

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: 3rd party build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      if: steps.cache-ext.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        cd .\wic_heic\3rdparty
        build.bat

    - name: Version Tagging
      if: github.ref_type == 'tag'
      run: |
        cd '.\Installer'
        $VER='${{ github.ref_name }}'.Replace('v','')
        (Get-Content Package.wxs).Replace('1.0.0', $VER) | Set-Content Package.wxs

    - name: Build x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x86 ${{env.SOLUTION_FILE_PATH}}

    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./(Build)
        retention-days: 1

    - name: Version Tagging
      if: github.ref_type == 'tag'
      run: |
        Rename-Item -Path ".\(Build)\x64\Release\en-US\WicHeic.msi" -NewName "WicHeic_${{ github.ref_name }}-x64.msi"
        Rename-Item -Path ".\(Build)\x86\Release\en-US\WicHeic.msi" -NewName "WicHeic_${{ github.ref_name }}-x86.msi"

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        body_path: CHANGELOG_LATEST.md
        files: |
          ./(Build)/x64/Release/en-US/wicheic_${{ github.ref_name }}-x64.msi
          ./(Build)/x86/Release/en-US/wicheic_${{ github.ref_name }}-x86.msi
